server:
  port: 8086

spring:
  application:
    name: SERVICE
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      port: 6379
      host: 43.201.195.182

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com:
      ssafy: trace

eureka:
  client:
#    register-with-eureka: false
    service-url:
      defaultZone: http://43.201.195.182:8761/eureka
  instance:
    prefer-ip-address: true

proxy:
  host: 121.162.108.65
  port: 9460

jasypt:
  password: ${PASSWORD}

nh:
  client:
    id: ENC(dDMftFuEktP7Xn7N3L/UElG0Ny0ZfNmVt0CJXzEND4teKt/qlX2tj73nIeN8EhVz)
    secret: ENC(p5Wn5A4yHMu4BGL+XMbzvpPYaTdEx82KK3hiNLdFHG2ODIRqBbIzmIn3UVmN/X7X)