server:
  port: 8086

spring:
  application:
    name: SERVICE
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      port: 6379
      host: 43.201.195.182
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(9pPcvFQrOmdd8PMOzb5LT2NO8knP5W7K75NVbQGuoMIDmdAnuDw2H6rFrUwwdM1pUQChn1uLuFr631F8gFMDxOlR4sG7I9kfO8F8lmCcdhmdHrTRbSTaHFMeCTZBwe7T)
    username: ENC(rgBkLekRUBVFezMhGqUMwQ==)
    password: ENC(2jZOoppfgHR24JO58hoYDN6Bk6UqkY1u)

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.type: WARN
    com.ssafy: Info
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN

eureka:
  client:
#    register-with-eureka: false
    service-url:
      defaultZone: http://43.201.195.182:8761/eureka
  instance:
    prefer-ip-address: true

proxy:
  host: 121.162.108.65
  port: 9460

jasypt:
  password: ${PASSWORD}

nh:
  client:
    id: ENC(dDMftFuEktP7Xn7N3L/UElG0Ny0ZfNmVt0CJXzEND4teKt/qlX2tj73nIeN8EhVz)
    secret: ENC(p5Wn5A4yHMu4BGL+XMbzvpPYaTdEx82KK3hiNLdFHG2ODIRqBbIzmIn3UVmN/X7X)

cloud:
  aws:
    credentials:
      accessKey: ENC(kMyHtS0sBPjSpalnnltB/nhyvfbEzJmM7zglZXOSDk8=)
      secretKey: ENC(qz+8NQvId9nLux7LonOIrfys3HlyM7bODKpkXiGNlEEPgKgBveEV0zHLwVpRYobaKS8KY02Bue4=)
    s3:
      bucket: a301-s3-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false