spring:
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6379
#  application:
#    name: ACCOUNT
#    h2:
#      console:
#        enabled: true
#        path: /h2
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#  sql:
#    init:
#      data-locations: classpath*:db/h2/data.sql
server:
  port: 8082
eureka:
  client:
    register-with-eureka: false