spring:
  application:
    name: ACCOUNT

  datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://a301-rds.cz4ggd8ra6pu.ap-northeast-2.rds.amazonaws.com:3306/account
      username: a301
      password: ssafyA301!
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
