spring:
#  cloud:
#    gateway:
#      routes:
#        - id: account
#          uri: lb://ACCOUNT/
#          predicates:
#            - Path=/account/**
#          filters:
#            - RewritePath=/account/(?<path>.*),/$\{path}
  application:
    name: API-GATEWAY
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
