server:
  port: 8761
spring:
  config:
    import: env.yml
  application:
    name: ${DOMAIN_NAME} # ??? ID
eureka:
  client:
    register-with-eureka: false # default : true
    fetch-registry: false # default : true
#    service-url:
#      defaultZone: ${EUREKA_URL}
