server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: notification
          uri: lb://NOTIFICATION/
          predicates:
            - Path=/notification/**
          filters:
            - RewritePath=/notification/(?<path>.*),/$\{path}
        - id: auth
          uri: lb://AUTH/
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*),/$\{path}
        - id: notice
          uri: lb://NOTICE/
          predicates:
            - Path=/notice/**
          filters:
            - RewritePath=/notice/(?<path>.*),/$\{path}
        - id: account
          uri: lb://ACCOUNT/
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/account/(?<path>.*),/$\{path}
  application:
    name: API-GATEWAY
eureka:
  client:
    service-url:
      defaultZone: http://43.201.195.182:8761/eureka
    fetch-registry: true
    register-with-eureka: true

