spring:
  cloud:
    gateway:
      routes:
        - id: notification
          uri: lb://NOTIFICATION/
          predicates:
            - Path=/notification/**
          filters:
            - RewritePath=/notification/(?<path>.*),/$\{path}
  application:
    name: API-GATEWAY
eureka:
  client:
    service-url:
      defaultZone: http://j9a301.p.ssafy.io:8761/euraka
