server:
  port: 8000

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
        - id: notification
          uri: lb://NOTIFICATION/
          predicates:
            - Path=/api/notification/**
          filters:
            - RewritePath=/api/notification/(?<path>.*),/$\{path}
        - id: auth
          uri: lb://AUTH/
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<path>.*),/$\{path}
        - id: notice
          uri: lb://NOTICE/
          predicates:
            - Path=/api/notice/**
          filters:
            - AuthFilter
            - RewritePath=/api/notice/(?<path>.*),/$\{path}
        - id: account
          uri: lb://ACCOUNT/
          predicates:
            - Path=/api/account/**
          filters:
            - RewritePath=/api/account/(?<path>.*),/$\{path}

  application:
    name: API-GATEWAY
eureka:
  client:
    service-url:
      defaultZone: http://43.201.195.182:8761/eureka
    fetch-registry: true
    register-with-eureka: true