spring :
  application:
    name: AUTH

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/auth
    username: root
    password: 1234
#  config:
#    import: env.yml
#  application:
#    name: ${DOMAIN_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_URL}

  data:
    redis:
      port: 6379
      host: 43.201.195.182

jwt:
  secretKey: all4u

  access:
    expiration: 3600000
    header: Authorization

  refresh:
    expiration: 1209600000
    header: Authorization-refresh