server:
  port: 8084

spring :
  application:
    name: AUTH

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://a301-rds.cz4ggd8ra6pu.ap-northeast-2.rds.amazonaws.com:3306/allforyou
    username: ENC(VNltww21CIXiNmgUXTMPOg==)
    password: ENC(TVzrKXINCXa2FQpT16WX1I3OCgHxPv3c)

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    redis:
      port: 6379
      host: 43.201.195.182

jwt:
  secretKey: ENC(7i9pXf0/gVyTyZOAh8gDVg==)

  access:
    expiration: 3600000
    header: Authorization

  refresh:
    expiration: 1209600000
    header: Authorization-refresh

eureka:
  client:
    service-url:
      defaultZone: http://43.201.195.182:8761/eureka
  instance:
    prefer-ip-address: true


jasypt:
  password: ${PASSWORD}

---

server:
  port: 8084

spring :
  config:
    activate:
      on-profile: dev

  application:
    name: AUTH

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://a301-rds.cz4ggd8ra6pu.ap-northeast-2.rds.amazonaws.com:3306/allforyou
    username: ENC(VNltww21CIXiNmgUXTMPOg==)
    password: ENC(TVzrKXINCXa2FQpT16WX1I3OCgHxPv3c)

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    redis:
      port: 6379
      host: 43.201.195.182

jwt:
  secretKey: ENC(7i9pXf0/gVyTyZOAh8gDVg==)

  access:
    expiration: 3600000
    header: Authorization

  refresh:
    expiration: 1209600000
    header: Authorization-refresh

eureka:
  client:
    register-with-eureka: false

jasypt:
  password: ${PASSWORD}