server:
  port: 8083

spring:
  application:
    name: NOTICE

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://a301-rds.cz4ggd8ra6pu.ap-northeast-2.rds.amazonaws.com:3306/notice
    username: ENC(VNltww21CIXiNmgUXTMPOg==)
    password: ENC(TVzrKXINCXa2FQpT16WX1I3OCgHxPv3c)
  #  config:
  #    import: env.yml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

eureka:
  client:
    service-url:
      defaultZone: http://43.201.195.182:8761/eureka

jasypt:
  password: ${PASSWORD}
