spring :
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://a301-rds.cz4ggd8ra6pu.ap-northeast-2.rds.amazonaws.com:3306/notice
    username: ENC(VNltww21CIXiNmgUXTMPOg==)
    password: ENC(TVzrKXINCXa2FQpT16WX1I3OCgHxPv3c)
  #  config:
  #    import: env.yml
  #  application:
  #    name: ${DOMAIN_NAME}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_URL}

jasypt:
  password: ${PASSWORD}